#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["RemoteAkkaTest.Api/RemoteAkkaTest.Api.csproj", "RemoteAkkaTest.Api/"]
COPY ["RemoteAkkaTest.Server/RemoteAkkaTest.Server.csproj", "RemoteAkkaTest.Server/"]

RUN dotnet restore "RemoteAkkaTest.Api/RemoteAkkaTest.Api.csproj"

COPY ["RemoteAkkaTest.Api/", "RemoteAkkaTest.Api/"]
COPY ["RemoteAkkaTest.Server/", "RemoteAkkaTest.Server/"]

RUN rm "RemoteAkkaTest.Server/appsettings.json"
RUN rm "RemoteAkkaTest.Server/appsettings.Development.json"

WORKDIR "/src/RemoteAkkaTest.Api"

RUN dotnet build "RemoteAkkaTest.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "RemoteAkkaTest.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "RemoteAkkaTest.Api.dll"]