version: "3.8"
services:
  server:
    build:
      context: ./RemoteAkkaTest.Server
      dockerfile: Dockerfile
    ports:
      - 8081:8081

  api:
    build:
      # context: ./RemoteAkkaTest.Api
      context: .
      dockerfile: Dockerfile-api
    ports:
      - 8000:80
      - 8001:443
      - 8080:8080
